# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'im_sure.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.PushButton_sure = PrimaryPushButton(Form)
        self.PushButton_sure.setGeometry(QtCore.QRect(220, 190, 153, 32))
        self.PushButton_sure.setObjectName("PushButton_sure")
        self.PrimaryPushButton_2 = PrimaryPushButton(Form)
        self.PrimaryPushButton_2.setGeometry(QtCore.QRect(20, 190, 153, 32))
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.StrongBodyLabel = StrongBodyLabel(Form)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(60, 40, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.StrongBodyLabel.setFont(font)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "确认入库"))
        self.PushButton_sure.setText(_translate("Form", "确定"))
        self.PrimaryPushButton_2.setText(_translate("Form", "取消"))
        self.StrongBodyLabel.setText(_translate("Form", "确定要将所扫描的商品入库吗？"))
from qfluentwidgets import PrimaryPushButton, StrongBodyLabel
