# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(617, 538)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 40, 280, 450))
        self.frame.setStyleSheet("border-image: url(:/images/images/bag.jpg);\n"
"border-top-left-radius:25px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(280, 40, 280, 450))
        self.frame_2.setMinimumSize(QtCore.QSize(280, 450))
        self.frame_2.setMaximumSize(QtCore.QSize(280, 450))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-bottom-right-radius:30px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(250, 0, 30, 30))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 211, 211);\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 0, 30, 30))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"    }\n"
"QPushButton:hover{\n"
"    background-color: rgb(211, 211, 211);\n"
"}")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 30, 261, 301))
        self.stackedWidget.setMinimumSize(QtCore.QSize(261, 301))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel = BodyLabel(self.page)
        self.BodyLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.EditableComboBox = EditableComboBox(self.page)
        self.EditableComboBox.setStyleSheet("LineEdit, TextEdit, PlainTextEdit {\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;\n"
"}\n"
"\n"
"TextEdit,\n"
"PlainTextEdit {\n"
"    padding: 2px 3px 2px 8px;\n"
"}\n"
"\n"
"LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"LineEdit:focus {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"    background-color: white;\n"
"}\n"
"\n"
"TextEdit:focus,\n"
"PlainTextEdit:focus {\n"
"    border-bottom: 1px solid #009faa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"LineEdit:disabled, TextEdit:disabled,\n"
"PlainTextEdit:disabled {\n"
"    color: rgba(0, 0, 0, 150);\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 13);\n"
"}\n"
"\n"
"#lineEditButton {\n"
"    background-color: transparent;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"#lineEditButton:hover {\n"
"    background-color: rgba(0, 0, 0, 9);\n"
"}\n"
"\n"
"#lineEditButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 6);\n"
"}\n"
"")
        self.EditableComboBox.setDragEnabled(False)
        self.EditableComboBox.setObjectName("EditableComboBox")
        self.verticalLayout.addWidget(self.EditableComboBox)
        self.PasswordLineEdit = PasswordLineEdit(self.page)
        self.PasswordLineEdit.setToolTip("")
        self.PasswordLineEdit.setStatusTip("")
        self.PasswordLineEdit.setAccessibleName("")
        self.PasswordLineEdit.setAutoFillBackground(False)
        self.PasswordLineEdit.setInputMask("")
        self.PasswordLineEdit.setText("")
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout.addWidget(self.PasswordLineEdit)
        self.CheckBox = CheckBox(self.page)
        self.CheckBox.setObjectName("CheckBox")
        self.verticalLayout.addWidget(self.CheckBox)
        self.PrimaryPushButton = PrimaryPushButton(self.page)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout.addWidget(self.PrimaryPushButton)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.LineEdit = LineEdit(self.page_2)
        self.LineEdit.setObjectName("LineEdit")
        self.verticalLayout_2.addWidget(self.LineEdit)
        self.LineEdit_2 = LineEdit(self.page_2)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.verticalLayout_2.addWidget(self.LineEdit_2)
        self.LineEdit_3 = LineEdit(self.page_2)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.verticalLayout_2.addWidget(self.LineEdit_3)
        self.PrimaryPushButton_2 = PrimaryPushButton(self.page_2)
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.verticalLayout_2.addWidget(self.PrimaryPushButton_2)
        self.stackedWidget.addWidget(self.page_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 380, 261, 61))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PushButton = PushButton(self.frame_3)
        self.PushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/sign-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButton.setIcon(icon2)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton, 0, QtCore.Qt.AlignVCenter)
        self.PushButton_2 = PushButton(self.frame_3)
        self.PushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButton_2.setIcon(icon3)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout.addWidget(self.PushButton_2, 0, QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 340, 261, 41))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2.raise_()
        self.frame.raise_()
        login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(login.showMinimized) # type: ignore
        self.pushButton.clicked.connect(login.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "test"))
        self.BodyLabel.setText(_translate("login", "欢迎登录"))
        self.EditableComboBox.setPlaceholderText(_translate("login", "用户名："))
        self.PasswordLineEdit.setPlaceholderText(_translate("login", "密码："))
        self.CheckBox.setText(_translate("login", "记住"))
        self.PrimaryPushButton.setText(_translate("login", "登录"))
        self.label_4.setText(_translate("login", "注册账户"))
        self.LineEdit.setPlaceholderText(_translate("login", "账户："))
        self.LineEdit_2.setPlaceholderText(_translate("login", "密码："))
        self.LineEdit_3.setPlaceholderText(_translate("login", "确认密码："))
        self.PrimaryPushButton_2.setText(_translate("login", "注册"))
from qfluentwidgets import BodyLabel, CheckBox, EditableComboBox, LineEdit, PasswordLineEdit, PrimaryPushButton, PushButton
import resource_rc
