# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AllScaner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllScaner(object):
    def setupUi(self, AllScaner):
        AllScaner.setObjectName("AllScaner")
        AllScaner.resize(808, 575)
        self.verticalLayout = QtWidgets.QVBoxLayout(AllScaner)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEdit = LineEdit(AllScaner)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PushButton = PushButton(AllScaner)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.PushButton_2 = PushButton(AllScaner)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout.addWidget(self.PushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TableWidget = TableWidget(AllScaner)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.TableWidget)
        self.CaptionLabel = CaptionLabel(AllScaner)
        self.CaptionLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.CaptionLabel.setText("")
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.verticalLayout_2.addWidget(self.CaptionLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.PrimaryPushButton = PrimaryPushButton(AllScaner)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout_2.addWidget(self.PrimaryPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(AllScaner)
        QtCore.QMetaObject.connectSlotsByName(AllScaner)

    def retranslateUi(self, AllScaner):
        _translate = QtCore.QCoreApplication.translate
        AllScaner.setWindowTitle(_translate("AllScaner", "Form"))
        self.PushButton.setText(_translate("AllScaner", "浏览"))
        self.PushButton_2.setText(_translate("AllScaner", "打开"))
        self.PrimaryPushButton.setText(_translate("AllScaner", "导出"))
from qfluentwidgets import CaptionLabel, LineEdit, PrimaryPushButton, PushButton, TableWidget
