# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Putaway.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_putaway(object):
    def setupUi(self, putaway):
        putaway.setObjectName("putaway")
        putaway.resize(556, 420)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(putaway)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEdit = LineEdit(putaway)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PushButton = PushButton(putaway)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ListWidget = ListWidget(putaway)
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout.addWidget(self.ListWidget)
        self.BodyLabel = BodyLabel(putaway)
        self.BodyLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(putaway)
        QtCore.QMetaObject.connectSlotsByName(putaway)

    def retranslateUi(self, putaway):
        _translate = QtCore.QCoreApplication.translate
        putaway.setWindowTitle(_translate("putaway", "Form"))
        self.PushButton.setText(_translate("putaway", "确定"))
from qfluentwidgets import BodyLabel, LineEdit, ListWidget, PushButton
