# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectStock.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectStock(object):
    def setupUi(self, SelectStock):
        SelectStock.setObjectName("SelectStock")
        SelectStock.resize(689, 413)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SelectStock)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEdit = LineEdit(SelectStock)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PushButton = PushButton(SelectStock)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.TableWidget = TableWidget(SelectStock)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.TableWidget)
        self.BodyLabel = BodyLabel(SelectStock)
        self.BodyLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.BodyLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SelectStock)
        QtCore.QMetaObject.connectSlotsByName(SelectStock)

    def retranslateUi(self, SelectStock):
        _translate = QtCore.QCoreApplication.translate
        SelectStock.setWindowTitle(_translate("SelectStock", "Form"))
        self.PushButton.setText(_translate("SelectStock", "查询"))
        self.BodyLabel.setText(_translate("SelectStock", "Body label"))
from qfluentwidgets import BodyLabel, LineEdit, PushButton, TableWidget
